### ISSUE TITLE
BAD_REQUEST_ERROR on checkout

### ISSUE THREAD

**Issue by Piyushborana111** [razorpay/razorpay-woocommerce#118] opened 2019-07-18 05:26 UTC
Hello, 
i installed razorpay for woocommerce currently entered test Api keys but when i try to purchase any product it give an error "Opps, something went wrong, The id provided does not exist"

**Comment by ramth05** [comment] 2019-07-29 10:40
looks like duplicate of #117. 
@Piyushborana111, can you please try the latest release. it must be fixed now.

**Comment by harman28** [comment] 2019-08-20 02:51
Fixed in latest version.

**Closed by harman28** 2019-08-20 02:51 UTC
